name: 'identity-app'
version: "3.9"

services:
    mongo-db:
        image: mongo:7.0
        command: ["--replSet", "rs0", "--bind_ip_all", "--port", "27017"]
        ports:
            - 27017:27017
        extra_hosts:
            - "host.docker.internal:host-gateway"
        healthcheck:
            test: echo "try { rs.status() } catch (err) { rs.initiate({_id:'rs0',members:[{_id:0,host:'host.docker.internal:27017'}]}) }" | mongosh --port 27017 --quiet
            interval: 5s
            timeout: 30s
            start_period: 0s
            start_interval: 1s
            retries: 30
        volumes:
            - "mongo1_data:/data/db"
            - "mongo1_config:/data/configdb"
    skeleton-svc:
        build: "../skeleton-svc"
        env_file:
            - "../skeleton-svc/.env.container"
        ports:
            - "3000:3000"
        depends_on: 
          mongo-db:
            condition: service_healthy

volumes:
  mongo1_data:
  mongo1_config: